routes/web.php
<?php

use App\Http\Controllers\addUserController;
use App\Http\Controllers\MainController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Models\Pizza;
use App\Models\User;
use App\Models\Photo;
use App\Models\Role;
use App\Models\Comment;
use App\Models\Post;
use App\Models\PostforonetomanyPhol;
use App\Models\Video;

use Illuminate\Auth\AuthenticationException;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome',['name'=>'ali']);
});
Route::get('/pizzas','App\Http\Controllers\PizzaController@index')->name('pizzas.index');//->middleware('auth');
Route::get('/pizzas/create','App\Http\Controllers\PizzaController@create')->name('pizzas.create');//->middleware('auth');//Ordenary run before the next step
Route::get('/pizzas/{id}','App\Http\Controllers\PizzaController@show')->name('pizzas.show');
Route::post('/pizzas','App\Http\Controllers\PizzaController@store')->name('pizzas.store');//->middleware('auth');//when i am in /pizzas and fill the field will run the store function and collaborate with @csrf ,  post /pizza combatableon form action..
Route::delete('/pizzas/{id}','App\Http\Controllers\PizzaController@destroy')->name('pizzas.destroy');//->middleware('auth');
// Route::get('/pizzas', function () {
//     //$pizza=['type'=>'pizzachikhen','size'=>'large','price'=>'110$'];
//     $pizzasVar=[
//     ['type'=>'holiwan','base'=>'Cheesy crest'],
//     ['type'=>'volcano','base'=>'garlic crest'],
//     ['type'=>'holiwan','base'=>'thin & crispy'] ];
//     $name=request('name');
//      return view('pizzas',
//      ['pizza'=> $pizzasVar,
//      'name'=>$name
//     ,'age'=>request("age")]); //detecte variable in url/name=dsd&age=34
//     //return "ali";
//     //return ['ali'=>'abodaraa','asem'=>'dribati']; //send Json
// });



 Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


//Route::redirect('/pizzas', '/');
Route::get('/home/{name}',function($username,$id=2) {
    $polo=['name'=>'aliabodaraaArray'];
    // return view('ali',compact('username','id')
    // ,['oo'=>$id,'name'=>'aliabodaraaArray','polo'=>$polo]);
    return view('ali',compact('username','id'),['oo'=>$id,'name'=>'mario','polo'=>$polo]);
});
Route::resource('/UDM',MainController::class);
Route::get('/insert',[MainController::class,'insert']);// /insertالى/posts/insertرح بدلstore($id)مشان ما ينفذ ال
Route::get('/update',[MainController::class,'updatePizza']);
Route::get('/updateInsert',[MainController::class,'updateInsert']);
Route::get('/delete',[MainController::class,'deletePizza']);

Route::get('/UDM/restore/{id}',function($id){
    Pizza::withTrashed()->where('id',$id)->restore();
    return redirect('/UDM')->with("mssg","Restore Done Now you can delete thi Row :)");
});
//Relationships
//OneToOne User photo
Route::get('/users',function(){
    return Photo::findOrFail(1)->user;
});

//OneToMany User Comments
 Route::get('/comments',function(){
     $comm= Comment::findOrFail(2);
     return $comm->user;
 });

//ManyToMany User roles
Route::get('/roles',function(){
    $user= User::findOrFail(55);
    return $user->roles;
});
//One to One polymorphic (User vs Photo) and (Post vs Photo) and ....
Route::get('user/{id}',function($id){
    $user=Post::find($id);
   $imagesUser= $user->photo;
   return  $imagesUser;
});
//One to Many polymorphic (Postfor.. vs commentfor..) and (Video vs commentfor..) and ....
Route::get('poly/{id}',function($id){
    $user=PostforonetomanyPhol::find($id);
   return $user->comments;
});
//One to Many polymorphic (Postfor.. vs commentfor..) and (Video vs commentfor..) and ....
Route::get('poly/{id}',function($id){
    $user=PostforonetomanyPhol::find($id);
   return $user->comments;
});
 //Many to MAny polymorphic (PostforonetomanyPhol vs Tags)and(Video vs Tags)
 Route::get('polyMany/{id}',function($id){
    $user=Video::find($id);
   return $user->tags;
});
//Accessors
Route::get('/user/name/{id}',function($id){
    $user=User::findOrFail($id);
   return $user->name;
});

//Mudutors
Route::resource('/User',addUserController::class);

//Auth
Auth::routes();//nessesaryto show register and login you can hide twice
//need use Illuminate\Support\Facades\Auth;
Route::get('/userlogin',function(){
    if(Auth::check()){//لاعرف اذا هوي حاليا مسجل دخول ولا لا
        return Auth::user();
    }else{return "this user not authenticated";}

   //return Auth::id();
});

resources/views/UDM/createPosts.blade.php
@extends('layouts.app')
@section('content')
 <h1>create Post</h1>
 <form action="/UDM" method="POST">
    @csrf
    <label for="name">Your Name:</label>
    <input type="text" name="name" id="name">
    <label for="name">The Price:</label>
    <input type="number" name="price" id="price">
    <label for="name">Choose Pizza Type:</label>
    <select name="type" id="type">
        <option value="margiraita">margiraita</option>
        <option value="veg sepreme">veg sepreme</option>
        <option value="volcano">volcano</option>
    </select>
    <label for="name">Choose Pizza base:</label>
    <select name="base" id="base">
        <option value="chessy grest">chessy grest</option>
        <option value="garlic crust">garlic crust</option>
        <option value="crespy">crespy</option>
    </select>
    <fieldset>
        <label></label>
        <input type="checkbox" name="tooping[]" value="mushroom">mushroom<br>
        <input type="checkbox" name="tooping[]" value="olives">olives<br>
        <input type="checkbox" name="tooping[]" value="garlic">garlic<br>
        <input type="checkbox" name="tooping[]" value="peppers">peppers<br>
        <input type="checkbox" name="tooping[]" value="onion">onion<br>
    </fieldset>
    <input type="submit" value="order Pizza" class="btn btn-success btn-block">

</form>



{{-- <p class="mssg">{{session('mssg')}}</p> --}}
@endsection

resources/views/UDM/index.blade.php
@extends('../layouts/app')
@section('content')



<div class="container">
    <p class="mssg" style="display:
    <?php
    if(!empty(session('mssg')))
    {echo 'block';}
    else{echo 'none';}
    ?>"> {{session('mssg')}}</p>
    <h1>UDM Index the best Pizza</h1>
    <button class="btn btn-primary btn-block"><a href='{{route('UDM.create')}}'>Create A New Order</a> </button>

            @foreach ($posts as $post)
            <div class="info">
                <p><span>ID: </span>{{$post->id}}</p>
                <p><span>NAME: </span>{{$post->name}}</p>
                <p><span>CREATED_AT: </span>{{$post->created_at}}</p>
                <p><span>PRICE: </span>{{$post->price}}</p>
                <p><span>TYPE: </span>{{$post->type}}</p>
                <ul>
                    <span>TOOPINGS: </span>
                @foreach ($post->tooping as $tooping)
                <li>
                    {{$tooping}}
                </li>

                @endforeach
                <button class="btn btn-success btn-block"><a href="UDM/{{$post->id}}/edit">Edit</a></button>

           {{-- for delete --}}
            <form action="/UDM/{{$post->id}}" method="POST">
                @csrf
                @method("DELETE")
              <input type="submit" value="Delete Row" name="delete" class="btn btn-danger btn-block">
            </form>
            </ul>

        </div>
            @endforeach




</div>
{{-- <a href="/pizzas/create" >Ordered A Pizza</a> --}}

@endsection

resources/views/UDM/show.blade.php
@extends('../layouts/app')
@section('content')



<div class="container">
    <h1>UDM Show For ID:{{$postshow->id}} the best Pizza</h1>


            <div class="info">
                <p><span>ID: </span>{{$postshow->id}}</p>
                <p><span>NAME: </span>{{$postshow->name}}</p>
                <p><span>CREATED_AT: </span>{{$postshow->created_at}}</p>
                <p><span>PRICE: </span>{{$postshow->price}}</p>
                <p><span>TYPE: </span>{{$postshow->type}}</p>
                <ul>
                <span>TOOPINGS: </span>
                @foreach ($postshow->tooping as $tooping)
                <li>
                    {{$tooping}}
                </li>

                @endforeach
                <button class="btn btn-success btn-block"><a href="{{$postshow->id}}/edit">Edit</a></button>
                <button class="btn btn-primary btn-block"><a href='{{route("UDM.create")}}'>Create A New Order</a> </button>
             {{-- for delete --}}
             <form action="/UDM/{{$postshow->id}}" method="POST">
                {{-- destroy($id)لانو الطريقه
               بهالشكل action بدها وسيط لهيم ال كان  --}}
                @csrf
                @method("DELETE")
              <input type="submit" value="Delete Row" name="delete" class="btn btn-danger btn-block">
            </form>
            </ul>

        </div>


            <a href="{{route('pizzas.create')}}" >Ordered A Pizza</a>


</div>


@endsection

resources/views/UDM/update.blade.php
@extends('layouts.app')
@section('content')

 <h1>Update Post it's ID:{{$posts->id}}</h1>
 <form action="/UDM/{{$posts->id}}" method="POST">
    {{-- /UDM/{{$posts->id}}هيك acionوصار بال UDM/{{$posts->id}}/edit لازم دائما نرجع بالمسار خطوه لورا لان مسار هالصفحه هوي --}}
    @csrf
   @method('PATCH') {{--  becase i edit fields isn't create fields --}}
    <label for="name">Your Name:</label>
    <input type="text" name="name" id="name" value='{{$posts->name}}'>
    <label for="name">The Price:</label>
    <input type="number" name="price" id="price" value='{{$posts->price}}'>
    <label for="name">Choose Pizza Type:</label>
    <select name="type" id="type" value='{{$posts->type}}'>
        <option value="margiraita">margiraita</option>
        <option value="veg sepreme">veg sepreme</option>
        <option value="volcano">volcano</option>
    </select>
    <label for="name">Choose Pizza base:</label>
    <select name="base" id="base" value='{{$posts->base}}'>
        <option value="chessy grest">chessy grest</option>
        <option value="garlic crust">garlic crust</option>
        <option value="crespy">crespy</option>
    </select>
   <fieldset class="gredaint">
    <label>Edit Tooping</label>
    <input type="checkbox" name="tooping[]" value="mushroom" {{(in_array('mushroom',$posts->tooping)) ?'checked':''}}>mushroom<br>
    <input type="checkbox" name="tooping[]" value="olives" {{(in_array('olives',$posts->tooping)) ?'checked':''}}>olives<br>
    <input type="checkbox" name="tooping[]" value="garlic" {{(in_array('garlic',$posts->tooping)) ?'checked':''}}>garlic<br>
    <input type="checkbox" name="tooping[]" value="peppers" {{(in_array('peppers',$posts->tooping)) ?'checked':''}}>peppers<br>
    <input type="checkbox" name="tooping[]" value="onion" {{(in_array('onion',$posts->tooping)) ?'checked':''}}>onion<br>
</fieldset>
    <input type="submit" value="order Pizza" class="btn btn-success btn-block">

</form>



{{-- <p class="mssg">{{session('mssg')}}</p> --}}
@endsection